In [4]:
x = 1
inputs = []
inputs.append(int(x == 2 - 1))
print(inputs)

[1]


In [ ]:
x = (1, 2)
y = (1, 2)
print(x + y)
print(x == y)


(1, 2, 1, 2)
True


In [ ]:
x = 1
y = 2
print(3 * (x == y))

0


: 

In [2]:
import random
import torch
from torch import nn

In [2]:
my_list = ['a', 'b', 'c', 'd', 'e']
all_indices = range(len(my_list))
sample_size = 3
sampled_indices = random.sample(all_indices, sample_size)
print(sampled_indices)

[0, 3, 2]


In [12]:
class NeuralNet(nn.Module):
  def __init__(self, in_dim, hidden_dim, out_dim):
    super(NeuralNet, self).__init__()
    self.linear1 = nn.Linear(in_dim, hidden_dim)
    self.linear2 = nn.Linear(hidden_dim, out_dim)
    self.softmax = nn.Softmax(dim=-1)
  
  def forward(self, normalized_inputs):
    normalized_inputs = self.linear1(normalized_inputs)
    normalized_inputs = self.linear2(normalized_inputs)
    output_probs = self.softmax(normalized_inputs)
    return output_probs

In [13]:
net = NeuralNet(40, 64, 1)
t = torch.rand(size=(10, 40))
o = net(t)
print(o.size())
print(o)

torch.Size([10, 1])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)


In [5]:
r = [1, 2, 3]
random.shuffle(r)
print(r)

[2, 3, 1]


In [6]:
t = torch.rand(size=(5, 5))
print(t)

tensor([[0.3452, 0.9166, 0.2036, 0.8587, 0.1148],
        [0.3738, 0.0280, 0.4534, 0.7073, 0.6830],
        [0.0029, 0.8664, 0.8477, 0.6528, 0.3144],
        [0.2225, 0.0706, 0.3197, 0.0487, 0.4688],
        [0.8040, 0.3235, 0.1428, 0.6921, 0.6145]])


In [11]:
i = torch.tensor([0, 1, 2, 3, 4], dtype=torch.long)
res = t.gather(dim=1, index=i.unsqueeze(1)).squeeze(1)
print(res)

tensor([0.3452, 0.0280, 0.8477, 0.0487, 0.6145])


In [21]:
print(list(range(5)))
print(random.sample(range(5), k=2))

[0, 1, 2, 3, 4]
[3, 2]


In [23]:
x = torch.tensor([1, 2, 3, 4, 5])
print(x.expand(5, -1))

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])
